(ns kanopi.client.functional-tests
  "Verify integrity of app state against an onslaught of input
  messages conceivably generated by a user. Further, verify request
  and response handlers tying everything together."
  (:require [com.stuartsierra.component :as component]
            [clojure.test :refer :all]
            [clojure.pprint :refer (pprint)]
            
            [schema.core :as s]
            
            [kanopi.system.server :as server]
            [kanopi.system.client :as client]
            
            ))

(deftest access-initial-session
  (let []
    ))

(deftest create-data
  (let []
    ))
